### ISSUE TITLE
비밀번호에 !가 있을 경우 @로 변경이 되버립니다.

### ISSUE THREAD

**Issue by eondcom** [poesis/xe-advanced-mailer#16]
암호에 !가 있을 경우 저장하면 @로 변경이 되버리는 문제가 있는데 한번 확인 부탁드리겠습니다.

**Comment by kijin** [comment]
문제가 재현되지 않습니다. SMTP 암호에 test! 라고 입력하고 저장 후 DB를 보니 test! 라고 정상적으로 입력되어 있고, 새로고침 후 소스보기를 해봐도 여전히 test! 입니다.
