### ISSUE TITLE
발송자 이름 - anonymous 표기 현상

### ISSUE THREAD

**Issue by DesignSORI** [poesis/xe-advanced-mailer#19]
안녕하세요. 좋은 모듈 잘 사용하고 있습니다.

각종 인증 메일들은 문제 없으나,
XE 게시판의 '알림' 기능을 이용할 때,

받는 측의 메일함에서 보낸이가 'anonymous'로 표기됩니다.

php mail() 함수를 사용할 경우에만 테스트 해보았습니다.

확인 부탁드립니다.

**Comment by kijin** [comment]
고급메일발송모듈은 코어에서 던져주는 메일을 그대로 받아서 발송할 뿐, 다른 모듈에서 보낸이 이름을 잘못 넣은 채 메일을 작성한 경우 일일이 수정해 주지는 않습니다. 만약 익명 게시판이라면 anonymous로 나오는 것이 정상일 수도 있습니다.
