### ISSUE TITLE
안내링크 수정필요

### ISSUE THREAD

**Issue by socialskyo** [poesis/xe-advanced-mailer#21]
![image](https://github.com/user-attachments/assets/b9bb5404-1a7b-4997-957f-395e99de2bf4)

의 링크가 동작하지 않는 기존 링크로 남아 있고 xe3 로 리다이렉트 되고 있습니다.

https://www.xpressengine.com/index.php?mid=download&package_id=22753677

**Comment by kijin** [comment]
어디에 나오는 안내인가요?

이 저장소는 지원이 중단된 XE 1.x용 고급 메일 발송 모듈입니다.

고급 메일 발송 모듈에서 고급 메일 발송 모듈을 쓰라고 안내하고 있을 것 같지는 않은데요.

**Comment by socialskyo** [comment]
> 어디에 나오는 안내인가요?
> 
> 이 저장소는 지원이 중단된 XE 1.x용 고급 메일 발송 모듈입니다.
> 
> 고급 메일 발송 모듈에서 고급 메일 발송 모듈을 쓰라고 안내하고 있을 것 같지는 않은데요.

알겠습니다. 그나저나 지원이 중단 안되거나 라이믹스용 고급 메일 발송 모듈 github가 있나보죠?

**Comment by kijin** [comment]
라이믹스는 advanced_mailer 모듈이 내장되어 있지요.^^
